print('Exercício 2')
print('Crie um script que leia o dia, o mês e o ano de nascimento de uma pessoa e mostre uma mensagem com a data formatada.')
dia = input('Em que dia você nasceu?')
mês = input('Em que mês você nasceu?')
ano = input('Em que ano você nasceu?')
print('Você nasceu dia', dia ,'de', mês ,'de', ano)
